spring:
  application:
    name: brewery-beer-service
  datasource:
    url: jdbc:h2:mem:brewery-beer-service;MODE=MYSQL
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  artemis:
    user: artemis-user
    password: artemis-password
  liquibase:
    change-log: classpath:db/changelog/dbchangelog-prod.xml
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
resilience4j:
  circuitbreaker:
    instances:
      inventory-service:
        minimumNumberOfCalls: 1
  timelimiter:
    instances:
      inventory-service:
        timeoutDuration: 10s

http-client:
  max-total: 50
  max-per-route: 20
  socket-timeout: PT5S
  idle-timeout: PT60S
  keep-alive-time: PT5S

queue:
  beer:
    brewing: beer-brewing
    validate: beer-validate
    validate-response: beer-validate-response
  inventory:
    add-stock: beer-inventory-add-stock

scheduler:
  lock-at-least-for: PT5M
  cron:
    inventory-checking: "0 0 */1 * * *"

rest:
  inventory:
    service: "http://localhost:8081/api/v1/inventories/"
  gateway:
    service: "http://localhost:9001/"