spring:
  application:
    name: brewery-beer-service
  datasource:
    url: jdbc:h2:mem:brewery-beer-service;MODE=MYSQL
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  artemis:
    user: artemis-user
    password: artemis-password

http-client:
  max-total: 50
  max-per-route: 20
  socket-timeout: PT5S
  idle-timeout: PT60S
  keep-alive-time: PT5S

queue:
  beer:
    brewing: beer-brewing

scheduler:
  cron:
    inventory-checking: "0 0 */1 * * *"