spring:
  application:
    name: brewery-beer-service
  datasource:
    url: jdbc:h2:mem:brewery-beer-service;MODE=MYSQL
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  artemis:
    user: artemis-user
    password: artemis-password
  liquibase:
    change-log: classpath:db/changelog/dbchangelog-local.xml

http-client:
  max-total: 50
  max-per-route: 20
  socket-timeout: PT5S
  idle-timeout: PT60S
  keep-alive-time: PT5S

queue:
  beer:
    brewing: beer-brewing
  inventory:
    add-stock: beer-inventory-add-stock

scheduler:
  lock-at-least-for: PT5M
  cron:
    inventory-checking: "0 */1 * * * *"

rest:
  inventory:
    service: "http://localhost:8081/api/v1/inventories/"

eureka:
  client:
    serviceUrl:
      defaultZone: http://netflix:eureka@localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true